import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from 'next/font/google'
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex-1 ">
        <Header />
        <main className="flex-1 overflow-hidden">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
